-- CREATE DATABASE DB_LOJA;

CREATE TABLE ROLES (
ID SERIAL PRIMARY KEY,
NOME TEXT NOT NULL UNIQUE,
ACESSO INTEGER NOT NULL
);


INSERT INTO ROLES (
  NOME,
  ACESSO
) VALUES (
  'ADMIN',
  1
);

INSERT INTO ROLES (
  NOME,
  ACESSO
) VALUES (
  'USER',
  3
);

CREATE TABLE USUARIOS (
ID SERIAL PRIMARY KEY,
NOME VARCHAR(100),
EMAIL VARCHAR(100) NOT NULL UNIQUE,
SENHA VARCHAR(100) NOT NULL,
ROLE INTEGER REFERENCES ROLES (ID)
);

CREATE TABLE PRODUTOS (
ID SERIAL PRIMARY KEY,
MARCA VARCHAR(150),
MODELO VARCHAR(200) NOT NULL,
QUANTIDADE INTEGER,
PRECO NUMERIC(15,2) NOT NULL,
ATIVO BOOLEAN DEFAULT TRUE
);